# Generated by Django 3.0 on 2021-01-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Start_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Задача')),
                ('content', models.TextField(verbose_name='Описание задачи')),
                ('created_dr', models.DateField(auto_now=True, verbose_name='Время создания')),
                ('created_up', models.DateField(auto_now_add=True, verbose_name='Время изминения')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Прикрепленное фото')),
                ('end_task', models.BooleanField(default=True, verbose_name='Завершить задачу?')),
            ],
        ),
    ]
